### ISSUE TITLE
bundle.js not found

### ISSUE THREAD

**Issue by no-liver** [chevalvert/boilerplate-kirby#1]
Hello,

For some reason the bundle.js file is not generated from the config
`p://localhost:8080/assets/builds/bundle.js net::ERR_ABORTED 404 (Not Found)`

Currently unable to pinpoint why the bundle.js file is not generated from the common.js file - can you advise?

**Comment by arnaudjuracek** [comment]
`bundle.js` is a remainder of an old version of this boilerplate, that I forgot to remove.

The current version accepts a list of JS entries defined in https://github.com/chevalvert/boilerplate-kirby/blob/main/config/webpack.config.common.js#L5-L8

You should then require `common.js`, `your-entry.js` and so on on your php templates.
This change as motivated by a thought on how to better link Kirby template system with a JavaScript view/component ecosystem.

Hope that clarify the question.
